- hosts: monitoring
  become: true
  tasks:

    - name: Disable IPv6
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6

    - name: Set DNS to Google
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNS='
        line: 'DNS=8.8.8.8'

    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted

    - name: Create docker app-network
      docker_network:
        name: app-network
        state: present

    - name: Clone monitoring tools repository
      become: true
      git:
        repo: https://github.com/GkG0139/int531-monitoring-tools.git
        dest: /home/ansible/int531-monitoring-tools
        version: main
        update: yes

    - name: Docker compose up monitoring stack
      community.docker.docker_compose_v2:
        project_src: /home/ansible/int531-monitoring-tools
        files:
          - services.compose.yml
          - monitoring.compose.yml
        state: present
