- name: Create VM on Proxmox
  hosts: localhost
  connection: local
  vars:
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Clone VM from template
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: "ubuntu-cloud-template-v3"
        name: "ansibleVm-{{ vm_create.vmid | default('NEW') }}"
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Get VM IP from guest agent
      command: qm agent {{ vm_create.vmid }} network-get-interfaces
      register: vm_network
      retries: 20
      delay: 15
      until: vm_network.stdout != ""
      ignore_errors: yes

    - name: Show raw guest agent output
      debug:
        var: vm_network.stdout

    - name: Parse VM IP from JSON
      set_fact:
        vm_ip: >-
          {% set data = vm_network.stdout | from_json %}
          {% set eth0 = data | selectattr("name", "equalto", "eth0") | list %}
          {% if eth0 | length > 0 and eth0[0]['ip-addresses'] | length > 0 %}
            {{ eth0[0]['ip-addresses'][0]['ip-address'] }}
          {% else %}
            ""
          {% endif %}

    - name: Fail if no IP found
      fail:
        msg: "Cannot determine VM IP via guest agent, set static IP or check qemu-guest-agent"
      when: vm_ip == ""

    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 300
        delay: 10
      delegate_to: "{{ vm_ip }}"

    - name: Add host to inventory
      add_host:
        name: "ansibleVm-{{ vm_create.vmid }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        groups: newly_created
