- name: Create VM on Proxmox
  hosts: localhost
  connection: local
  vars:
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Clone VM from template
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: "ubuntu-cloud-template-v3"
        name: "ansibleVm-{{ vm_create.vmid | default('NEW') }}"
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Get VM IP from guest agent
      command: qm agent {{ vm_create.vmid }} network-get-interfaces
      register: vm_network
      retries: 10
      delay: 15
      until: vm_network.stdout != ""
      ignore_errors: yes

    - name: Parse VM IP from JSON
      set_fact:
        vm_ip: "{{ (vm_network.stdout | from_json).result[0]['ip-addresses'][0]['ip-address'] | default('DHCP_UNKNOWN') }}"

    - name: Wait for SSH to become available
      wait_for_connection:
        host: "{{ vm_ip }}"
        timeout: 300

    - name: Add host to inventory
      add_host:
        name: "ansibleVm-{{ vm_create.vmid }}"
        ansible_host: "{{ vm_ip }}"    # เอา IP จริงของ VM
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        groups: newly_created
