- name: Create VM on Proxmox
  hosts: localhost
  connection: local
  vars:
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Clone VM from template
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: "ubuntu-cloud-template-v3"
        name: "ansibleVm-{{ vm_create.vmid | default('NEW') }}"
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 300
        sleep: 10
      delegate_to: "ansibleVm-{{ vm_create.vmid | default('NEW') }}"

    - name: Add host to inventory
      add_host:
        name: "ansibleVm-{{ vm_create.vmid }}"
        ansible_host: "{{ vm_ip }}"    # เอา IP จริงของ VM
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        groups: newly_created
