- name: Create VM on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Clone VM from template
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: "ubuntu-cloud-template-v3"
        name: "ansibleVm-{{ vm_create.vmid | default('NEW') }}"
        ciuser: sysadmin
        cipassword: "int53104"
        sshkeys: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Rename VM using qm set
      command: qm set {{ vm_create.vmid }} --name ansibleVm-{{ vm_create.vmid }}

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Wait for VM guest agent to be ready
      shell: |
        until qm agent {{ vm_create.vmid }} ping 2>/dev/null; do sleep 5; done
      retries: 20
      delay: 15
      register: agent_ready
      ignore_errors: yes

    - name: Get VM IP from guest agent
      command: qm agent {{ vm_create.vmid }} network-get-interfaces
      register: vm_network
      retries: 20
      delay: 15
      until: vm_network.stdout != ""
      ignore_errors: yes

    - name: Parse VM IP from JSON
      set_fact:
        vm_ip: >-
          {% set data = vm_network.stdout | from_json %}
          {% set eth0 = data | selectattr("name", "equalto", "eth0") | list %}
          {% if eth0 | length > 0 and eth0[0]['ip-addresses'] | length > 0 %}
            {{ eth0[0]['ip-addresses'][0]['ip-address'] | trim | replace('\r','') }}
          {% else %}
            ""
          {% endif %}

    - name: Fail if no IP found
      fail:
        msg: "Cannot determine VM IP via guest agent, set static IP or check qemu-guest-agent"
      when: vm_ip == ""

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        state: started
        timeout: 300

    - name: Ensure sysadmin user exists
      ansible.builtin.user:
        name: sysadmin
        shell: /bin/bash
        state: present
        create_home: yes
      delegate_to: "{{ vm_ip | trim }}"

    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: /home/sysadmin/.ssh
        state: directory
        owner: sysadmin
        group: sysadmin
        mode: '0700'
      delegate_to: "{{ vm_ip | trim }}"

    - name: Add SSH public key for sysadmin user
      ansible.builtin.authorized_key:
        user: sysadmin
        key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        state: present
      delegate_to: "{{ vm_ip | trim }}"

    - name: Ensure home directory has correct permissions
      ansible.builtin.file:
        path: /home/sysadmin
        owner: sysadmin
        group: sysadmin
        mode: '0700'
      delegate_to: "{{ vm_ip | trim }}"

    - name: Ensure sshd_config allows public key authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        backup: yes
      delegate_to: "{{ vm_ip | trim }}"

    - name: Ensure AuthorizedKeysFile is correct in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysFile'
        line: 'AuthorizedKeysFile      .ssh/authorized_keys .ssh/authorized_keys2'
        state: present
        backup: yes
      delegate_to: "{{ vm_ip | trim }}"

    - name: Restart SSH to apply changes
      ansible.builtin.service:
        name: ssh
        state: restarted
      become: yes
      delegate_to: "{{ vm_ip | trim }}"

    - name: Create .ssh folder for sysadmin
      ansible.builtin.file:
        path: /home/sysadmin/.ssh
        state: directory
        owner: sysadmin
        group: sysadmin
        mode: 0700
      delegate_to: "{{ vm_ip | trim }}"

    - name: Add SSH public key for sysadmin user
      ansible.builtin.copy:
        content: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        dest: /home/sysadmin/.ssh/authorized_keys
        owner: sysadmin
        group: sysadmin
        mode: 0600
      delegate_to: "{{ vm_ip | trim }}"

    - name: Restart SSH service on VM
      ansible.builtin.service:
        name: ssh
        state: restarted
      become: true
      delegate_to: "{{ vm_ip | trim }}"

    - name: Add host to inventory
      add_host:
        name: "{{ vm_ip | trim }}"
        ansible_host: "{{ vm_ip | trim}}"
        ansible_user: sysadmin
        ansible_ssh_private_key_file: /root/.ssh/ansible
        groups: newly_created
