- name: Create VM on Proxmox
  hosts: localhost
  connection: local
  vars:
    vm_name: ansibleVm
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Clone VM from template 7002
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: "ubuntu-cloud-template-v3"
        name: "{{ vm_name }}"
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Wait VM boot
      pause:
        seconds: 30

    - name: Wait for VM IP via Proxmox guest agent
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: current
      register: vm_info
      retries: 10
      delay: 15
      until: vm_info.agent_interfaces is defined and vm_info.agent_interfaces | length > 0

    - name: Get VM guest agent info
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: info
      register: vm_info

    - name: Show VM info
      debug:
        var: vm_info

    - name: Add new VM to inventory
      add_host:
        name: "{{ vm_info.data.name }}"
        ansible_host: "{{ vm_info.data.ips[0].ip | regex_replace('/.*','') }}"
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        groups: newly_created
