- name: Set up virtual machine on Proxmox
  hosts: localhost
  connection: local
  vars:
    vm_name: ansibleVm
    vm_template: ubuntu-cloud-template-v2
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Create VM from template (Cloud-Init + DHCP)
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        clone: "{{ vm_template }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        ciuser: ansible
        cipassword: int53104
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Wait for VM to boot
      pause:
        seconds: 30

    - name: Get VM info
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        name: "{{ vm_name }}"
        state: current
      register: vm_info

    - name: Set VM IP fact
      set_fact:
        vm_ip: "{{ vm_info.proxmox_agent_interfaces[0]['ip-addresses'][0]['ip-address'] }}"

- name: Configure VM with Ansible roles
  hosts: localhost
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "{{ playbook_dir }}/privatekey"
  tasks:
    - block:
        - name: Wait for SSH
          wait_for_connection:
            delay: 15
            timeout: 600
          delegate_to: "{{ vm_ip }}"

        - name: Run roles
          delegate_to: "{{ vm_ip }}"
          become: true
          include_role:
            name: "{{ item }}"
          loop:
            - common
            - monitor
            - app
      rescue:
        - name: Delete VM on failure
          community.proxmox.proxmox_kvm:
            api_user: root@pam
            api_password: int53104
            api_host: 10.13.104.214
            vmid: "{{ vm_create.vmid }}"
            state: absent
