- name: Set up virtual machine on Proxmox
  hosts: localhost
  connection: local
  vars:
    vm_name: ansibleVm
    vm_template: ubuntu-cloud-template-v2
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Get VM current state
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: current
      register: vm_info
      ignore_errors: true

    - name: Remove VM if exists
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: absent
      when: vm_info.vmid is defined

    - name: Create VM from template (Cloud-Init + DHCP)
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        clone: "{{ vm_template }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        update: true

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: started
        
- name: Configure VM with Ansible roles
  hosts: proxmox_all_running
  become: true
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "{{ playbook_dir }}/privatekey"
  tasks:
    - name: Wait for SSH to be available
      wait_for_connection:
        delay: 10
        timeout: 300
  roles:
    - common
    - monitor
    - app
