- name: Set up virtual machine on Proxmox
  hosts: localhost
  connection: local
  vars:
    vm_name: ansibleVm
    vm_template: ubuntu-cloud-template-v2
    proxmox_node: int531-04
    proxmox_api_host: 10.13.104.214
    proxmox_api_user: root@pam
    proxmox_api_password: int53104

  tasks:
    - name: Create VM from template (Cloud-Init + DHCP)
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        clone: "{{ vm_template }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        ciuser: ansible
        cipassword: int53104
        ipconfig:
          ipconfig0: "ip=dhcp"
        agent: 1
        timeout: 600
      register: vm_create

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ vm_create.vmid }}"
        state: started

    - name: Get Proxmox ticket
      uri:
        url: "https://{{ proxmox_api_host }}:8006/api2/json/access/ticket"
        method: POST
        body: "username={{ proxmox_api_user }}&password={{ proxmox_api_password }}"
        validate_certs: false
      register: ticket_info

    - name: Wait for VM to get IP
      uri:
        url: "https://{{ proxmox_api_host }}:8006/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_create.vmid }}/agent/network-get-interfaces"
        method: POST
        headers:
          Cookie: "PVEAuthCookie={{ ticket_info.json.data.ticket }}"
          X-CSRFPreventionToken: "{{ ticket_info.json.data.CSRFPreventionToken }}"
        validate_certs: false
      register: agent_info
      ignore_errors: true
      until: (agent_info.status | default(0) == 200) and (agent_info.json.result | selectattr('name', 'equalto', 'eth0') | map(attribute='ip-addresses') | flatten | selectattr('type', 'equalto', 'ipv4') | map(attribute='ip-address') | length > 0)
      retries: 30
      delay: 10

    - name: Set VM IP fact
      set_fact:
        vm_ip: "{{ (agent_info.json.result | selectattr('name', 'equalto', 'eth0') | map(attribute='ip-addresses') | flatten | selectattr('type', 'equalto', 'ipv4') | map(attribute='ip-address') | first) }}"

- name: Configure VM with Ansible roles
  hosts: localhost
  become: true
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "{{ playbook_dir }}/privatekey"
  tasks:
    - block:
        - name: Wait for SSH to be available
          wait_for_connection:
            delay: 10
            timeout: 300
        - name: Include roles
          include_role:
            name: "{{ item }}"
          loop:
            - common
            - monitor
            - app
      delegate_to: "{{ vm_ip }}"
      become: true
      rescue:
        - name: Delete VM on failure
          community.proxmox.proxmox_kvm:
            api_user: root@pam
            api_password: int53104
            api_host: 10.13.104.214
            vmid: "{{ vm_create.vmid }}"
            state: absent
          run_once: true
