
- name: Set up virtual machine on Proxmox
  hosts: localhost
  vars:
    vm_name: ansibleVm
    vm_template: ubuntu-cloud-template-v2
    proxmox_node: int531-04 
    proxmox_api_host: 10.13.104.214 
    proxmox_api_user: root@pam
    proxmox_api_password: int53104 
    proxmox_storage: local-lvm

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Get VM current state
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: current
      register: vm_info
      ignore_errors: true

    - name: Stop the VM if running
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: stopped
        force: true
      when: vm_info.vmid is defined and vm_info.status ==  'running'

    - name: Remove VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ vm_name }}"
        node: "{{ proxmox_node }}"
        state: absent
      when: vm_info.vmid is defined

    - name: Create VM from template
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_api_host }}"
        clone: ubuntu-cloud-template
        name: ansibleVm
        node: int531-04
        ciuser: ansible
        cipassword: int53104
        sshkeys: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        cores: 2
        memory: 2048
        update: true

    - name: Update VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        name: "{{ vm_name }}"
        ciuser: ansible 
        cipassword: int53104 
        sshkeys: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIi6WnsbU+MM356oCy6Gz9KD5BW8gnhowhFuhAhpX4sC sysadmin@10.13.104.224
'
        ipconfig:
          ipconfig0: 'ip=dhcp,gw=10.13.104.254'
        update: yes

    - name: Start VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ new_vm.vmid }}"
        node: "{{ proxmox_node }}"
        state: started

    - name: Get VM IP
      community.proxmox.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        name: "{{ vm_name }}"
        state: current
      register: vm_info

    - name: Remove old SSH host key
      ansible.builtin.known_hosts:
        name: "{{ vm_info }}"
        state: absent


- name: Configure VM with Ansible roles
  hosts: proxmox_all_running
  become: true
  roles:
    - common
    - monitor
    - app
